### ISSUE TITLE
Support for Event Espresso 4 Ticket Scanning

### ISSUE THREAD

**Issue by garthkoyle** [eventespresso/eea-rest-api#31]
We need to provide support for scanning a bar/qr code(s) that are generated via the Ticket Scanning add-on.

I hope we don't have to build our own mobile apps, but rather encourage other mobile app developers to provide support for the awesome apps they have already built.
- http://eventespresso.com/wiki/barcode-scanner-add-on/
- https://eventespresso.com/product/eea-barcode-scanner/

For check-ing in attendees, I presume we want the api to function just the same as the Scanning add-on does. Scanning a ticket once gives you options to check-in attendees, subsequent scans give you more options, etc. 

@nerrad anything you want to add here? What information do you think we need to discuss?

**Comment by mnelson4** [comment]
yeah specifically what INFO is contained in the QR codes?

**Comment by nerrad** [comment]
The QR codes encode the `EEM_Registration::reg_url_lnk`,  Barcodes will either be `EEM_Registration::reg_code` or `EEM_Registration::reg_url_lnk` depending on how users setup the barcode generation.

So for the purpose of this ticket the api doesn't really need to do anything specific for scanning.  Anything built _using_ the api would:
- need to scan barcodes (using whatever native scanner library they use) to grab the reg_url_lnk or reg_code
- Use the READ facility on the EE API to grab the related registration information (if doing a lookup).
- And then just use the WRITE endpoints for the api to do whatever they want to do once they know the reg info.

So as an example use case where an app is being used to check in people for an event:
- scan the code (app's responsibility)
- hit a GET endpoint for grabbing registration data (facilitated by our API)
- display info to user in app with a ui for "checking in" the registration (app's responsibility), 
- app can then send data to a PUT endpoint for updating the related checkin record for the registration/evt/datetime.

So bottom line, if the phase 2 of the api adds write capabilities for all EEM_Models (which is what I think you've already planned on doing) then any app developer will have all they need for building an app to check-in people.

The _only_ specific thing I can think of that you might want to include when building the write endpoints (which you may have already planned for) is to allow users to update based on criteria other than primary key (in this case REG_ID).  For example the app may have facility for just checking in users in one go using the reg_url_lnk or reg_code.

I'm assuming you already understand this Mike but am writing more for Garth's and others benefit:

> I presume we want the api to function just the same as the Scanning add-on does. Scanning a ticket once gives you options to check-in attendees, subsequent scans give you more options, etc.

Usually, an HTTP API has nothing to do with the functionality of a _consumer_ (in this case, a consumer is a mobile application which allows event organizers to check-in attendees).  The HTTP API is merely an interface for getting/writing/updating data via an explained structure.  So as we build the api, as long as we're exposing the data via endpoints, consumers (app builders) should be able to build whatever they want :)

The statement I highlighted from your post is a description of _consumer_ behaviour not _api_ behaviour. So practically speaking, the only thing we need to be concerned about here is that we are exposing the data people need to build such an app.  The good news, is that we're already about 50% there because the necessary READ endpoints are complete.

**Comment by mnelson4** [comment]
we built our own mobile apps so I think this is basically invalidated
