### ISSUE TITLE
Retrieving event custom fields

### ISSUE THREAD

**Issue by ganeshcodes** [eventespresso/eea-rest-api#37]
Hi All,
I am using EE4 for creating events. I have installed Event Espresso - REST API (EE4.x+) and WP REST API plugins for fetching the events data. I have created two custom fields (presenters, presenter_details). 

URL : /wp-json/ee/v4.6/events?include=Venue._,Datetime._,Extra_Meta.*

I am getting the events details along with Venues and Datetimes but extra_metas is null. I expected those custom fields to come as a part of extra metas. Then I tried hitting the extra_meta link directly, but I received 403. Below are the details,

URL : /wp-json/ee/v4.6/events/32/extra_metas 
Headers : Authorization (base64 encoding of username:password)
Response : [{"code":"json_extra_metas_cannot_list","message":"Sorry, you are not allowed to list extra_metas related to Extra_Meta. Missing permissions: manage_options"}]

I am getting 403 for above even for admin credentials. This issue is due to the basic authentication failing or am I missing something else? I have installed and activated JSON Basic Authentication plugin for basic auth support for wp-json api. Any help would be highly appreciated. Thanks!

**Comment by mnelson4** [comment]
> I have created two custom fields

do you mean you added these fields from the wp dashboard while editing the event? https://drive.google.com/file/d/0B2KCao4zFjaxWU53Yi11eDVDdlU/view?usp=drivesdk

If so they've actually been added as post meta, not extra meta (basically, "extra meta" is intended for all the EE things that don't already have a way to store meta info; and because custom post types and users already have a way to store custom meta, it's not included).
...And actually wp postmeta isn't accessible via the wp api by default either! yuck. 
So this is definetely something we need; of course we also don't want to accidentally expose postmetas that are sensitive to unauthenticated users (for example, I think some folks put their paypal ID as a custom field on certain events). So we'll probably want to have a list of public postmeta data, but authenticated users should be able to see it all. So I'll need to chat with the other developers about adding this, and update this ticket.

Regarding 

> Sorry, you are not allowed to list extra_metas related to Extra_Meta

First off that error message isn't quite right is it? It should read "extra_metas related to Events".
And you should be able to acccess them if you've logged in properly, which it sounds like you aren't. I'm guessing you're experiencing this issue: https://github.com/WP-API/Basic-Auth/issues/12
The solution seems pretty simple and I opened a pull request here: https://github.com/WP-API/Basic-Auth/pull/18
In the meantime you can try using our forked version of the basic auth plugin here: https://github.com/eventespresso/Basic-Auth (if it works for you too, chime in on the pull request and ask it get merged into the main basic-auth plugin).

**Comment by mnelson4** [comment]
oh actually my apologies: if you're authenticated you CAN currently get postmeta data from the normal wp api, although it's not exposed terribly obviously. You can use the url `{site_url}/wp-json/posts/{id}/meta`.
So for each event that you want postmeta for, you currently will need to send a separate request to:
`{site_url}/wp-json/posts/{event_id}/meta` to get that event's post meta. Make sense?
I know it's not the most convenient way to get at the custom fields; we'll work on a better method

**Comment by ganeshcodes** [comment]
Thanks for your response. I tried the forked version of basic auth plugin and tried hitting the api call from Advanced rest client with admin credentials. Now it's working. This should be merged into main basic-auth plugin. And as you said, custom fields didn't come in extra_metas. So I need to hit two resource urls to fetch the all events details. 

URL 1 : https://localhost/wordpress/wp-json/ee/v4.6/events?include=Venue._,Datetime._ 
URL 2 : https://localhost/wordpress/wp-json/posts/{EVT_ID}/meta  

Though it works, It involves multiple api calls. The problem is that I need to hit a different url for each event to access custom fields. If I have 50 events in my site, I need to make 50 extra calls to access its respective meta data ?! 

With that being said, It would be helpful if there is a way to get meta data/custom fields in a single api call along with Venues and Datetimes. Thanks.

**Comment by mnelson4** [comment]
>  I tried the forked version of basic auth plugin and tried hitting the api call from Advanced rest client with admin credentials. Now it's working

Please tell the basic auth plugin author: https://github.com/WP-API/Basic-Auth/pull/18
I agree it should be merged but so far haven't heard back. I think it would help to have someone else confirm it works.

> Though it works, It involves multiple api calls. The problem is that I need to hit a different url for each event to access custom fields....

yeah it's obviously not the model of efficiency. We'll work on a solution for you (and everyone else who will be wanting postmeta for their events, venues, and attendees) but it needs to weighed against other priorities. I'll update this ticket with the changes

**Comment by mnelson4** [comment]
ACTUALLY, we've had this work done quite a while now, but it's just been awaiting testing. @ganeshbabu91 would you be wiling to do some testing to help get the work merged into core?

**Comment by ganeshcodes** [comment]
> Please tell the basic auth plugin author: WP-API/Basic-Auth#18

I have requested the basic auth plugin author to merge this to the master two days ago. 

> ACTUALLY, we've had this work done quite a while now, but it's just been awaiting testing.

Could you let me know approximately when the solution would be available for us to use? I am definitely willing to do some testing. Let me know how could I help you.

**Comment by mnelson4** [comment]
it's available for testing now actually!

In event-espresso-core, checkout the branch BUG-8587-add-post-meta-model. Note that this based off our upcoming 4.8 release which is currently in beta. So when you switch to this branch, it will require running some data migration scripts. You'll need to run those before continuing to use EE.

Once you've switched the core branch and ran the migrations, you'll be able to make a query like the following, and when you're logged in, and see all the postmeta: `{site_url}/wp-json/ee/v4.8/events?include=Post_Meta` it should include all the event's post meta info.
(Currently you can also use `{site_url}/wp-json/ee/v4.7/events?include=Post_Meta` but that should actually be disabled because we want to only add new stuff onto new endpoints; it's preferred to keep the 4.6 and 4.7 endpoints the same for as long as possible for backwards compatibility).

Additionally, we also need to verify these changes don't break a few key aspects of event espresso core. So please confirm:
- [ ] You can still use this branch of EE to create a test event, and create a registration for it
- [ ] Verify that you can still trash that event, the new registration, and the new contact/attendee. Also if it allows you to permanently delete the registration (by going to "registrations" then "trashed" and clicking "delete")

If the above two tests are ok, then we should be able to get this merged into our main 4.8 beta branch, BETA-4.8-CORE, and have it released along with the rest of 4.8.

**Comment by mnelson4** [comment]
well BUG-8587-add-post-meta-model has been merged into 4.8.18 so this issue should be resolved
