### ISSUE TITLE
EE4 decaf v9.0 vs eea-rest-api v3.0.1 vs WP-Rest-Api

### ISSUE THREAD

**Issue by giovannasg** [eventespresso/eea-rest-api#43]
I have a site with "wp 4.52". Today i have installed "ee4decaf version 4.9" and when i active
"Event Espresso 4 - Events REST API - Versione: 3.0.1.beta.003" the wp-api doesn't function.
Every route (for example the main "wp-json/posts") show a route error.
If i deactive the plugin ee3-rest-api, all it's okay.
Is there a compatibility problem? 
thanks

**Comment by mnelson4** [comment]
the ee4-rest-api addon is deprecated, see https://eventespresso.com/2016/01/rest-api-now-in-ee4-core/.
Do you need to use the WP API v1 (which is also deprecated, see http://wp-api.org/index-deprecated.html where it mentions that it's "legacy")? Or is it an option to use WP API v2?

The EE4 REST API included in EE4 since 4.8.29 is compatible with WP API v2. See https://github.com/eventespresso/event-espresso-core/blob/master/docs/C--REST-API/ee4-rest-api-introduction.md

**Comment by giovannasg** [comment]
I'have upgraded my site to "wp api v2", deinstalled the ee2-rest-api addon and all it'ok
thanks for information

**Comment by mnelson4** [comment]
no problem; sorry I noticed that I don't think we mentioned anywhere on this repo that it's deprecated
