### ISSUE TITLE
Apply permissions/caps to READING the API

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/eea-rest-api#8]
permissions should be take into account when:
- [x] determining if the current user can access an endpoint at ALL (including the config endpoint)
- [x] determining if the current user can GET a particular entity after it's been retrieved from the DB (ie a request to events/1 should return 403 if it exists but the current user can't access it; not just a 404 saying it wasn't found)
- [x] building database queries
- [x] determining which fields should be returned even if the current user has permission to see an item
- [x] construct permissions array
- [x] document permissions
- [x] add unit tests to verify the permissions are respected

And have a plan for: (but not necessarily fully implement)
- [x] determining if the current user can create new items
- [x] determining if the current user can update a specific item
- [x] determining if the current user can update a particular field? eg, you might be able to edit a question, but unable to change which user it is associated with. That might require another permission

**Comment by mnelson4** [comment]
stuff I still need to figure out: 
- [x] what if we're returning, say, a registration, and the user indicates to include each registration's attendee, but the user doesn't have permission to see the attendee? What should be returned? A WP_Error? (kinda nice and specific, not sure how that will convert into json) or null? (doesn't indicate if they have permission or not to see it; but simple)

**Comment by mnelson4** [comment]
Should use https://docs.google.com/a/eventespresso.com/spreadsheets/d/1paQ8gdiZmIpOTJetRtk0_7GZfsWIXkioqrWmXxS4FZo/edit#gid=1 for determing how permissions act

**Comment by nerrad** [comment]
One consideration is how we save "authorship" for registrations and contacts.
- When a registration is created it's "author" is the author of the event the registration belongs to.
- The INITIAL contact is authored by the event the contact belongs to for the initial registration and thereafter doesn't change (which isn't so useful when a contact belongs to multiple registrations across multiple events).

So in the case of registrations, determining access is as easy as ensuring that the user is the author of the event and/or has permissions to read/edit others registrations.

With contacts its a bit trickier.  I suggest that:
- If the contact belongs to a registration that the user has access to then they can READ it (and you can return the contact object).
- However if the contact also belongs to OTHERs registrations, then the user can only EDIT the contact if they have the edit_contact capability.  Otherwise they can edit contact that contact without the edit_contact capability.  That's a tad bit different than the way EE admin does it, but it might work well for the api?

I noticed that we DON'T have ee_edit_others_contacts.  We might want to add that to core.  That would allow us to restrict the ability to edit contacts ONLY if all registrations on that contact belong to the user OR they have the `ee_edit_others_contacts` capability.

**Comment by mnelson4** [comment]
yeah good point @nerrad, sounds like adding an ee_edit_others_contacts cap would be good, but either way that'l probably be best to address that once I'm working on #20, whereas this ticket is just focused on permissions relating to reading, not editing

**Comment by nerrad** [comment]
Understood, but a `ee_read_others_contacts` would likely be good to have as well?

**Comment by mnelson4** [comment]
yeah that's a good point; that would make sense. Should we also consider adding `ee_read_others_questions`, `ee_read_others_question_types`, `ee_read_others_transactions`, `ee_read_others_payments`, `ee_read_others_prices`, `ee_read_others_price_types`, `ee_read_others_questions`, and others?
Also it's probably worth mentioning that many permissions apply to the admin, but might not apply normally to the API. Eg, `ee_read_events`: we might be tempted to say "if the current user doesn't have ee_read_events, they can't read ANY events, because they can't read any events normally in EE", but that's actually only true for the admin: a user without `ee_read_events` actually CAN read events on the frontend. So actually if they don't have `ee_read_events` we probably just want to limit them to viewing published events. (And if someone wants to view the exact same set as in the backend, we can provide a filter like "admin=1" to have the two match. eh?)

**Comment by nerrad** [comment]
yeah DEFINITELY worth considering "others" caps elsewhere (I think some of those mentioned already exist).  Keep in mind tho, we can only use "others" type caps when we save author information to the db for each object.

> Also it's probably worth mentioning that many permissions apply to the admin, but might not apply normally to the API. Eg, ee_read_events: we might be tempted to say "if the current user doesn't have ee_read_events, they can't read ANY events, because they can't read any events normally in EE", but that's actually only true for the admin: a user without ee_read_events actually CAN read events on the frontend. So actually if they don't have ee_read_events we probably just want to limit them to viewing published events. (And if someone wants to view the exact same set as in the backend, we can provide a filter like "admin=1" to have the two match. eh?)

That's what I was kinda getting at in chat the other day about having an "admin" context for endpoints to use.  So when that context is used then we require auth for those requests and return data based on permissions on the authed user.  Otherwise we treat the endpoints as "public" context which behaves as you described.  I think there's value in indicating `admin` context via the endpoint itself. So as an example:

```
https://api.domain.com/v1/admin/events
```

requires an authed user, and will only return event objects that user has permissions to read. vs.

```
https://api.domain.com/v1/events
```

does not require an authed user, and will return published event info (with publicly accessible field/related object values).

**Comment by mnelson4** [comment]
> Keep in mind tho, we can only use "others" type caps when we save author information to the db for each object.
> Well actually with some of the work in codebase ticket 7914, if a model doesn't have a foreign key to the wp_users table itself, we can define a related model that does. Eg, registrations don't have a foreign key to wp_users, but events do: so the registration's "owner" is determined by the event's owner.

re using

> https://api.domain.com/v1/admin/events

Yeah that's what I understood. I created #21 for that specifically

**Comment by nerrad** [comment]
huh, I thought registrations did have a wp_user filed, but nope they don't, but yeah I like how you're talking.

**Comment by mnelson4** [comment]
ok so currently branch FET-8-integrate-core-7976 works with core FET-7976-permissions-defined-in-models. But with regards to applying capabilities to the models I think it's mostly there: you can specify admin, read, or even edit or delete contexts for your queries, and we are filtering out fields you shouldn't be able to read (which right now appear to just be post-content fields' raw values).

**Comment by mnelson4** [comment]
once the core branch that this depends on is merged in I'll close this
